Server:
  port: 9999
  rootgroup: "/douyin"

Log:
  maxSize: 100 # 日志文件最大尺寸（M）
  maxBackups: 10 # 保留旧文件的最大个数
  maxAge: 10 # 保留旧文件的最大天数
  developMode: true

DB:
  dsn : "root:shouwangpigu233@tcp(127.0.0.1:3306)/tiktok_project?charset=utf8mb4&parseTime=True&loc=Local"
  maxIdleConns : 10 # 最大空闲连接数
  maxOpenConns : 10 # 最大打开连接数
  